"""
role_mappings.py — Mapping from service name patterns to role identifiers.

All patterns are evaluated in order — last match wins.
"""

ROLE_MAPPINGS = {
    "Backup server": "VBRBACKUPSERVER",
    "%plug-in%": "VBRBACKUPSERVER",
    "Veeam backup & replication console": "VBRCONSOLE",
    "Backup repository": "VBRBACKUPREPOSITORY",
    "Backup repository or gateway server": "VBRBACKUPREPOSITORY",
    "Backup repository or gateway server working with backup repository": "VBRBACKUPREPOSITORY",
    "Source backup repository": "VBRBACKUPREPOSITORY",
    "Target backup repository": "VBRBACKUPREPOSITORY",
    "Backup repository (microsoft windows)": "VBRBACKUPREPOSITORYWINDOWS",
    "Backup repository (linux)": "VBRBACKUPREPOSITORYLINUX",
    "Backup repository (source)": "VBRBACKUPREPOSITORY",
    "Backup repository (target)": "VBRBACKUPREPOSITORY",
    "Mount server": "VBRMOUNTSERVER",
    "Backup proxy%": "VBRBACKUPPROXY",
    "Guest interaction proxy%": "VBRGIP",
    "Tape Server": "TAPESERVER",
    "Esxi server": "VMWAREESXI",
    "Esxi host": "VMWAREESXI",
    "Vcenter server": "VMWAREVCENTER",
    "Microsoft windows server with the mount server role running vpower nfs service": "VBRPOWERNFS",
    "Smtp server": "SMTPSERVER",
    "Syslog server": "SYSLOG",
    "Veeam update notification server%": "VEEAMUPDATE",
    "Veeam signature update server": "VEEAMUPDATESIGNATURE",
    "Veeam license update server%": "VEEAMLICENSE",
    "Veeam ai assistant%": "VEEAMAI",
    "Esxi host (source)": "VMWAREESXICDP",
    "Esxi host (target)": "VMWAREESXICDP",
    "Esxi host (source and target)": "VMWAREESXICDP",
    "Vcenter server (source and target)": "VMWAREVCENTERCDP",
    "Cdp proxy %": "VBRCDPPROXY",
    "WAN accelerator%": "VBRWANACCELERATOR",
    "MS SQL VM guest OS": "VMSQLSERVER",
    "VM guest OS": "VMGUESTOS",
    "VM guest OS (Microsoft Windows)": "VMGUESTOSWINDOWS",
    "VM guest OS (Linux)": "VMGUESTOSLINUX",
    "VM guest OS (Linux/Unix)": "VMGUESTOSLINUX",
    "Log Shipping server": "VBRLOGSHIPPING",
}
